# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/authRouter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user/authRouter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import token_pb2 as common_dot_token__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user/authRouter.proto\x12\x04user\x1a\x12\x63ommon/token.proto\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t2E\n\x0b\x41uthService\x12\x36\n\x05Login\x12\x12.user.LoginRequest\x1a\x19.common.JustTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.authRouter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=51
  _globals['_LOGINREQUEST']._serialized_end=98
  _globals['_AUTHSERVICE']._serialized_start=100
  _globals['_AUTHSERVICE']._serialized_end=169
# @@protoc_insertion_point(module_scope)
