# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user/authRouter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user/authRouter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import token_pb2 as common_dot_token__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15user/authRouter.proto\x12\x04user\x1a\x12\x63ommon/token.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Y\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x13\n\x0blanguage_id\x18\x04 \x01(\x05\"%\n\x15\x41pproveAccountRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"|\n\x1c\x41\x64\x64itionalInformationRequest\x12\x11\n\tpronounce\x18\x01 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x02 \x01(\t\x12\x0b\n\x03sex\x18\x03 \x01(\t\x12,\n\x08\x62irthday\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x99\x02\n\x0b\x41uthService\x12\x36\n\x05Login\x12\x12.user.LoginRequest\x1a\x19.common.JustTokenResponse\x12\x38\n\x08Register\x12\x15.user.RegisterRequest\x1a\x15.common.TokenWithText\x12\x44\n\x0e\x41pproveAccount\x12\x1b.user.ApproveAccountRequest\x1a\x15.common.TokenWithText\x12R\n\x15\x41\x64\x64itionalInformation\x12\".user.AdditionalInformationRequest\x1a\x15.common.TokenWithTextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user.authRouter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=84
  _globals['_LOGINREQUEST']._serialized_end=131
  _globals['_REGISTERREQUEST']._serialized_start=133
  _globals['_REGISTERREQUEST']._serialized_end=222
  _globals['_APPROVEACCOUNTREQUEST']._serialized_start=224
  _globals['_APPROVEACCOUNTREQUEST']._serialized_end=261
  _globals['_ADDITIONALINFORMATIONREQUEST']._serialized_start=263
  _globals['_ADDITIONALINFORMATIONREQUEST']._serialized_end=387
  _globals['_AUTHSERVICE']._serialized_start=390
  _globals['_AUTHSERVICE']._serialized_end=671
# @@protoc_insertion_point(module_scope)
