# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proto/user/user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'app/proto/user/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import token_pb2 as app_dot_proto_dot_common_dot_token__pb2
from app.proto.common import common_pb2 as app_dot_proto_dot_common_dot_common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pp/proto/user/user.proto\x1a\x1c\x61pp/proto/common/token.proto\x1a\x1d\x61pp/proto/common/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x13\n\x0bkeepLogined\x18\x03 \x01(\x08\x32\x37\n\nUserRouter\x12)\n\x05Login\x12\r.LoginRequest\x1a\x11.TokenAndUserDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.proto.user.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=119
  _globals['_LOGINREQUEST']._serialized_end=187
  _globals['_USERROUTER']._serialized_start=189
  _globals['_USERROUTER']._serialized_end=244
# @@protoc_insertion_point(module_scope)
