# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat/chat.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'chat/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.proto.common import common_pb2 as common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63hat/chat.proto\x1a\x13\x63ommon/common.proto\"$\n\x13\x43hatQuestionRequest\x12\r\n\x05query\x18\x01 \x01(\t\"k\n\x14\x43hatQuestionResponse\x12\x11\n\x07message\x18\x01 \x01(\tH\x00\x12\x36\n\x0e\x65rror_response\x18\x02 \x01(\x0b\x32\x1c.common.DefaultErrorResponseH\x00\x42\x08\n\x06result2J\n\x0b\x43hatService\x12;\n\x0c\x43hatQuestion\x12\x14.ChatQuestionRequest\x1a\x15.ChatQuestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATQUESTIONREQUEST']._serialized_start=40
  _globals['_CHATQUESTIONREQUEST']._serialized_end=76
  _globals['_CHATQUESTIONRESPONSE']._serialized_start=78
  _globals['_CHATQUESTIONRESPONSE']._serialized_end=185
  _globals['_CHATSERVICE']._serialized_start=187
  _globals['_CHATSERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
